import { app } from "../../scripts/app.js";
import { CATEGORIES, ALL_STYLE_LABELS, MODIFIER_AXES, ARTIST_LABELS } from "./stylebook_widgets.js";

/*
 * Stylebook frontend extension.
 *
 * All features degrade gracefully: any failure is caught so the node
 * still works headless. The gallery, dependent dropdowns, and
 * mode-gated widget hiding live here.
 *
 * Generated data (CATEGORIES, STYLE_LABELS, etc.) lives in
 * stylebook_widgets.js — regenerated by scripts/generate_js_data.py.
 */

app.registerExtension({
    name: "stylebook.gallery",
    async setup() {
        // Future: register gallery dialog.
    },
    async nodeCreated(node) {
        // Future: widget visibility gating based on mode.
    },
});
