import { app } from "../../scripts/app.js";
import {
  CATEGORIES,
  STYLE_DATA_BY_CATEGORY,
  ALL_STYLE_LABELS,
} from "./stylebook_widgets.js";

/*
 * Stylebook frontend extension.
 *
 * Two features, both wrapped in try/catch so a frontend failure
 * never breaks the node:
 *
 *   1. Modal gallery dialog (class StylebookGallery below). Opened
 *      by a button widget attached to every StylebookStyle node;
 *      clicking a tile sets the style widget and switches mode to
 *      Pick so the choice is immediately visible/applied.
 *
 *   2. Mode-gated widget visibility. The mode combo controls which
 *      sibling widgets are relevant: `style` only matters in Pick;
 *      `category`/`tag_filter` only matter in Random/Cycle/Sheet;
 *      `cycle_index` only in Cycle; `sheet_count` only in Sheet.
 *      We hide by swapping `type` to a placeholder and zeroing
 *      `computeSize`, matching the Identity Forge pattern, so the
 *      hidden widget's value still round-trips through the saved
 *      workflow.
 *
 * Generated data (CATEGORIES, STYLE_LABELS, etc.) lives in
 * stylebook_widgets.js - regenerated by scripts/generate_js_data.py.
 * The export block in that file is outside the GENERATED DATA markers
 * and is added by hand to expose the data as ES module named exports.
 */

const EXT_NAME = "stylebook.gallery";
const MODE_PICK = "Pick";
const MODE_RANDOM = "Random";
const MODE_CYCLE = "Cycle";
const MODE_SHEET = "Sheet";
const WIDGET_HIDDEN_TYPE = "if_hidden";
const CSS_MARKER_ATTR = "data-stylebook-gallery";

// --- CSS injection --------------------------------------------------------

function injectCSS() {
  if (document.querySelector("[" + CSS_MARKER_ATTR + "]")) return;
  let href;
  try {
    href = new URL("./stylebook_gallery.css", import.meta.url).href;
  } catch (_) {
    href = "./stylebook_gallery.css";
  }
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = href;
  link.setAttribute(CSS_MARKER_ATTR, "1");
  document.head.appendChild(link);
}

// --- Widget hiding (Identity Forge pattern, namespaced) -------------------

function hideWidget(w) {
  if (!w || w.__stylebookHidden) return;
  w.__stylebookHidden = true;
  w.__stylebookOrigType = w.type;
  w.__stylebookOrigComputeSize = w.computeSize;
  w.type = WIDGET_HIDDEN_TYPE;
  w.computeSize = function () { return [0, -4]; };
}

function showWidget(w) {
  if (!w || !w.__stylebookHidden) return;
  w.__stylebookHidden = false;
  if (w.__stylebookOrigType) w.type = w.__stylebookOrigType;
  if (typeof w.__stylebookOrigComputeSize === "function") {
    w.computeSize = w.__stylebookOrigComputeSize;
  }
  w.__stylebookOrigType = null;
  w.__stylebookOrigComputeSize = null;
}

function resize(node) {
  if (!node) return;
  if (typeof node.computeSize === "function") {
    try {
      const sz = node.computeSize();
      const w = (node.size && node.size[0]) || 0;
      node.setSize([Math.max(w, sz[0]), sz[1]]);
    } catch (_) { /* ignore */ }
  }
  if (typeof node.setDirtyCanvas === "function") {
    try { node.setDirtyCanvas(true, true); } catch (_) { /* ignore */ }
  }
}

function setWidgetValue(node, w, value) {
  if (!w) return;
  w.value = value;
  if (typeof w.callback === "function") {
    try { w.callback(value, app.canvas, node); } catch (_) { /* ignore */ }
  }
}

// --- Style data helpers ---------------------------------------------------

function categoryDisplayName(cat) {
  return String(cat)
    .split("_")
    .filter(Boolean)
    .map(function (s) { return s.charAt(0).toUpperCase() + s.slice(1); })
    .join(" ");
}

function getStylesForCategory(cat) {
  const data = STYLE_DATA_BY_CATEGORY[cat];
  if (!data || !Array.isArray(data.labels) || !Array.isArray(data.ids)) return [];
  const out = [];
  for (let i = 0; i < data.labels.length; i++) {
    out.push({ id: data.ids[i], label: data.labels[i] });
  }
  return out;
}

function getAllStyles() {
  const out = [];
  for (const cat of CATEGORIES) {
    for (const s of getStylesForCategory(cat)) {
      out.push({ id: s.id, label: s.label, category: cat });
    }
  }
  return out;
}

function styleMatches(style, query) {
  if (!query) return true;
  const q = query.toLowerCase();
  if ((style.label || "").toLowerCase().indexOf(q) !== -1) return true;
  if ((style.id || "").toLowerCase().indexOf(q) !== -1) return true;
  if ((style.category || "").toLowerCase().indexOf(q) !== -1) return true;
  // The "id" already covers snake_case tokens. categoryDisplayName covers
  // the friendly form ("film cinema" matches "film_cinema").
  if (categoryDisplayName(style.category || "").toLowerCase().indexOf(q) !== -1) return true;
  return false;
}

function tileInitials(label) {
  const parts = String(label || "").split(/[\s&/.\-()]+/).filter(Boolean);
  const initials = parts.slice(0, 2).map(function (w) { return w.charAt(0).toUpperCase(); }).join("");
  return initials || "?";
}

// --- Widget lookup --------------------------------------------------------

function findStylebookWidgets(node) {
  if (!node || !Array.isArray(node.widgets)) return null;
  const byName = {};
  for (const w of node.widgets) if (w && w.name) byName[w.name] = w;
  const mode = byName["mode"];
  if (!mode || !mode.options || !Array.isArray(mode.options.values)) return null;
  // "Pick" + "Sheet" are the most distinctive values for our node;
  // checking both avoids matching any random node that happens to have
  // a "mode" widget.
  if (!mode.options.values.includes(MODE_PICK)) return null;
  if (!mode.options.values.includes(MODE_SHEET)) return null;
  return {
    mode: mode,
    style: byName["style"] || null,
    category: byName["category"] || null,
    tagFilter: byName["tag_filter"] || null,
    cycleIndex: byName["cycle_index"] || null,
    sheetCount: byName["sheet_count"] || null,
    seed: byName["seed"] || null,
  };
}

// --- Visibility logic -----------------------------------------------------

function updateVisibility(widgets) {
  if (!widgets || !widgets.mode) return;
  const mode = widgets.mode.value;
  const isPick = mode === MODE_PICK;
  const isRandom = mode === MODE_RANDOM;
  const isCycle = mode === MODE_CYCLE;
  const isSheet = mode === MODE_SHEET;
  const isFilterMode = isRandom || isCycle || isSheet;

  // style dropdown: only in Pick
  if (widgets.style) (isPick ? showWidget : hideWidget)(widgets.style);
  // category + tag_filter: only in filter modes
  if (widgets.category) (isFilterMode ? showWidget : hideWidget)(widgets.category);
  if (widgets.tagFilter) (isFilterMode ? showWidget : hideWidget)(widgets.tagFilter);
  // cycle_index: only in Cycle
  if (widgets.cycleIndex) (isCycle ? showWidget : hideWidget)(widgets.cycleIndex);
  // sheet_count: only in Sheet
  if (widgets.sheetCount) (isSheet ? showWidget : hideWidget)(widgets.sheetCount);
}

function setupModeCallback(node, widgets) {
  if (!widgets || !widgets.mode) return;
  const modeW = widgets.mode;
  const prev = modeW.callback;
  modeW.callback = function (value) {
    if (typeof prev === "function") {
      try { prev.apply(this, arguments); } catch (_) { /* ignore */ }
    }
    try { updateVisibility(widgets); resize(node); } catch (err) {
      console.error("[" + EXT_NAME + "] updateVisibility failed:", err);
    }
  };
  try { updateVisibility(widgets); } catch (err) {
    console.error("[" + EXT_NAME + "] initial updateVisibility failed:", err);
  }
}

// --- Gallery dialog -------------------------------------------------------

class StylebookGallery {
  constructor(node) {
    this.node = node;
    const widgets = node.widgets || [];
    this.styleWidget = widgets.find(function (w) { return w && w.name === "style"; }) || null;
    this.modeWidget = widgets.find(function (w) { return w && w.name === "mode"; }) || null;
    this.activeCategory = CATEGORIES[0] || null;
    this.query = "";
    this.overlay = null;
    this.dialog = null;
    this.searchInput = null;
    this.gridEl = null;
    this.tabsEl = null;
    this.countEl = null;
  }

  open() {
    if (this.overlay) return; // already open
    try {
      this.buildDOM();
      document.body.appendChild(this.overlay);
    } catch (err) {
      console.error("[" + EXT_NAME + "] failed to open gallery:", err);
      this.close();
      return;
    }
    // Focus search after the browser has had a chance to lay out the dialog.
    const self = this;
    requestAnimationFrame(function () {
      try { if (self.searchInput) self.searchInput.focus(); } catch (_) { /* ignore */ }
    });
  }

  close() {
    if (this.overlay && this.overlay.parentNode) {
      this.overlay.parentNode.removeChild(this.overlay);
    }
    this.overlay = null;
    this.dialog = null;
    this.searchInput = null;
    this.gridEl = null;
    this.tabsEl = null;
    this.countEl = null;
  }

  buildDOM() {
    const overlay = document.createElement("div");
    overlay.className = "stylebook-gallery-overlay";

    const dialog = document.createElement("div");
    dialog.className = "stylebook-gallery-dialog";
    dialog.setAttribute("role", "dialog");
    dialog.setAttribute("aria-label", "Stylebook Style Gallery");
    dialog.setAttribute("aria-modal", "true");

    // --- header (search + count) ---
    const header = document.createElement("div");
    header.className = "stylebook-gallery-header";

    const search = document.createElement("input");
    search.type = "text";
    search.className = "stylebook-gallery-search";
    search.placeholder = "Search styles by name, alias, or category...";
    search.spellcheck = false;
    search.autocomplete = "off";
    const self = this;
    search.addEventListener("input", function (e) {
      self.query = e.target.value || "";
      self.renderGrid();
    });
    this.searchInput = search;

    const count = document.createElement("span");
    count.className = "stylebook-gallery-count";
    this.countEl = count;

    header.appendChild(search);
    header.appendChild(count);

    // --- tabs ---
    const tabs = document.createElement("div");
    tabs.className = "stylebook-gallery-tabs";
    tabs.setAttribute("role", "tablist");
    this.tabsEl = tabs;

    // --- grid ---
    const grid = document.createElement("div");
    grid.className = "stylebook-gallery-grid";
    grid.setAttribute("role", "listbox");
    this.gridEl = grid;

    // --- footer ---
    const footer = document.createElement("div");
    footer.className = "stylebook-gallery-footer";
    footer.textContent = "Stylebook - offline, dependency-free, model-agnostic. Preview images coming soon.";

    dialog.appendChild(header);
    dialog.appendChild(tabs);
    dialog.appendChild(grid);
    dialog.appendChild(footer);
    overlay.appendChild(dialog);

    // Backdrop click closes; clicks inside the dialog must not bubble to
    // the canvas (which would deselect the node and look like a bug).
    overlay.addEventListener("mousedown", function (e) {
      if (e.target === overlay) self.close();
    });
    overlay.addEventListener("click", function (e) { e.stopPropagation(); });
    // Capture-phase Escape so it works regardless of which child has focus.
    overlay.addEventListener("keydown", function (e) {
      if (e.key === "Escape") {
        e.preventDefault();
        e.stopPropagation();
        self.close();
      }
    }, true);

    this.overlay = overlay;
    this.renderTabs();
    this.renderGrid();
  }

  renderTabs() {
    if (!this.tabsEl) return;
    this.tabsEl.innerHTML = "";
    const self = this;
    for (const cat of CATEGORIES) {
      const btn = document.createElement("button");
      btn.type = "button";
      btn.className = "stylebook-gallery-tab" + (cat === this.activeCategory ? " active" : "");
      btn.textContent = categoryDisplayName(cat);
      btn.setAttribute("role", "tab");
      btn.setAttribute("aria-selected", cat === this.activeCategory ? "true" : "false");
      btn.addEventListener("click", function () {
        if (self.activeCategory === cat) return;
        self.activeCategory = cat;
        self.query = "";
        if (self.searchInput) self.searchInput.value = "";
        self.renderTabs();
        self.renderGrid();
      });
      this.tabsEl.appendChild(btn);
    }
  }

  renderGrid() {
    if (!this.gridEl) return;
    this.gridEl.innerHTML = "";
    // Alias before any closure capture so the filter/map callbacks below
    // can read it (arrow functions would work too, but the rest of the
    // file uses `function () { ... }` + `self` for consistency).
    const self = this;

    const all = this.query
      ? getAllStyles().filter(function (s) { return styleMatches(s, self.query); })
      : getStylesForCategory(this.activeCategory).map(function (s) {
          return { id: s.id, label: s.label, category: self.activeCategory };
        });


    if (this.countEl) {
      this.countEl.textContent = all.length + " style" + (all.length === 1 ? "" : "s");
    }

    if (!all.length) {
      const empty = document.createElement("div");
      empty.className = "stylebook-gallery-empty";
      empty.textContent = this.query
        ? 'No styles match "' + this.query + '".'
        : "No styles in this category.";
      this.gridEl.appendChild(empty);
      return;
    }

    for (const style of all) {
      this.gridEl.appendChild(this.buildTile(style));
    }
  }

  buildTile(style) {
    const tile = document.createElement("button");
    tile.type = "button";
    tile.className = "stylebook-gallery-tile";
    tile.setAttribute("role", "option");
    tile.setAttribute("data-category", style.category || "");
    tile.setAttribute("data-style-id", style.id || "");
    tile.setAttribute("aria-label", style.label || "");
    tile.title = style.label || "";

    if (this.styleWidget && this.styleWidget.value === style.label) {
      tile.classList.add("selected");
    }

    const placeholder = document.createElement("div");
    placeholder.className = "stylebook-gallery-tile-placeholder";
    placeholder.textContent = tileInitials(style.label);

    const label = document.createElement("div");
    label.className = "stylebook-gallery-tile-label";
    label.textContent = style.label || "";

    tile.appendChild(placeholder);
    tile.appendChild(label);

    const self = this;
    tile.addEventListener("click", function () { self.selectStyle(style); });

    return tile;
  }

  selectStyle(style) {
    try {
      // Switch mode to Pick so the style widget is visible and applied.
      if (this.modeWidget && this.modeWidget.value !== MODE_PICK) {
        setWidgetValue(this.node, this.modeWidget, MODE_PICK);
      }
      if (this.styleWidget) {
        setWidgetValue(this.node, this.styleWidget, style.label);
        showWidget(this.styleWidget);
      }
      // Re-apply visibility using the freshest widget references (the
      // mode callback already did this, but a manual select might happen
      // before any callback fires).
      const widgets = findStylebookWidgets(this.node);
      if (widgets) updateVisibility(widgets);
      resize(this.node);
    } catch (err) {
      console.error("[" + EXT_NAME + "] failed to apply style:", err);
    }
    this.close();
  }
}

// --- Per-node setup -------------------------------------------------------

const setupDone = new WeakSet();

function setupStylebookNode(node) {
  if (!node || setupDone.has(node)) return;
  const widgets = findStylebookWidgets(node);
  if (!widgets) return;
  setupDone.add(node);

  setupModeCallback(node, widgets);

  // Attach a button widget that opens the gallery. serialize:false keeps
  // the button out of the saved workflow JSON (mirrors identity_forge).
  try {
    const gallery = new StylebookGallery(node);
    const button = node.addWidget(
      "button",
      "Open Style Gallery",
      null,
      function () {
        try { gallery.open(); }
        catch (err) { console.error("[" + EXT_NAME + "] open failed:", err); }
      },
      { serialize: false }
    );
    if (button) button.__stylebookGallery = gallery;
    // First-time resize so the new button doesn't get clipped.
    resize(node);
  } catch (err) {
    console.error("[" + EXT_NAME + "] failed to attach gallery button:", err);
  }
}

// --- Extension registration ------------------------------------------------

app.registerExtension({
  name: EXT_NAME,
  async setup() {
    try { injectCSS(); }
    catch (err) { console.error("[" + EXT_NAME + "] CSS injection failed:", err); }
  },
  async nodeCreated(node) {
    try { setupStylebookNode(node); }
    catch (err) { console.error("[" + EXT_NAME + "] nodeCreated failed:", err); }
  },
});
