"""Generate the frontend's data module from the Python data layer.

Writes ``js/stylebook_data.js``, which is generated in full and contains
nothing hand-written. The gallery code lives in ``js/stylebook_gallery.js``
and this script never touches it.

An earlier revision generated into the middle of a hand-edited file and
overwrote the whole thing, silently deleting the ``export`` statements
the gallery imported. That broke the entire frontend, and ``--check``
still passed, because it only compared the generated block against a
fresh render of itself. Keeping generated and hand-written code in
separate files removes that failure mode entirely.

Usage:
    python scripts/generate_js_data.py            # write
    python scripts/generate_js_data.py --check    # verify (CI gate)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

TARGET = ROOT / "js" / "stylebook_data.js"
PREVIEW_INDEX = ROOT / "js" / "previews" / "index.json"

HEADER = """\
// Generated by scripts/generate_js_data.py. Do not edit by hand.
// Regenerate after changing anything under data/:
//     python scripts/generate_js_data.py
//
// This entire file is generated. Hand-written frontend code belongs in
// stylebook_gallery.js, which the generator never touches.
"""


def _js(value: object) -> str:
    """Render a Python value as JSON, which is valid JS for these shapes."""
    return json.dumps(value, ensure_ascii=False)


def _preview_sprites() -> dict:
    """Reshape the preview index into responsive sprite coordinates.

    The gallery sizes its tiles with a CSS grid, so they are not a fixed
    pixel width. CSS percentage ``background-size`` is measured against
    the element rather than the image, which means a tile grid can only
    be addressed in grid units: an atlas that is ``cols`` tiles wide is
    scaled to ``cols * 100%`` of the tile, and each tile is then reached
    with a percentage position. Emitting column/row indices instead of
    pixels keeps that arithmetic on this side and shrinks the payload.
    """
    if not PREVIEW_INDEX.is_file():
        return {}

    raw = json.loads(PREVIEW_INDEX.read_text(encoding="utf-8"))
    out: dict[str, dict] = {}
    for category, entry in raw.get("categories", {}).items():
        tiles = entry.get("tiles", {})
        if not tiles:
            continue
        first = next(iter(tiles.values()))
        tile_w, tile_h = first.get("w", 256), first.get("h", 256)
        if not tile_w or not tile_h:
            continue
        cols = max(t["x"] + t["w"] for t in tiles.values()) // tile_w
        rows = max(t["y"] + t["h"] for t in tiles.values()) // tile_h
        out[category] = {
            "atlas": entry.get("atlas", f"{category}.webp"),
            "cols": cols,
            "rows": rows,
            "tiles": {
                sid: [t["x"] // tile_w, t["y"] // tile_h]
                for sid, t in tiles.items()
            },
        }
    return {"model": raw.get("model", ""), "categories": out}


def generate() -> str:
    from data.artists import (
        ARTIST_CATEGORIES, ARTIST_CATEGORY_LABELS, ARTISTS,
    )
    from data.modifiers import AXES, MODIFIERS, MODIFIERS_BY_AXIS
    from data.styles import CATEGORIES, CATEGORY_LABELS, STYLES

    styles_by_category: dict[str, dict[str, list]] = {}
    for category in CATEGORIES:
        ids = [sid for sid, rec in STYLES.items() if rec.get("category") == category]
        styles_by_category[category] = {
            "ids": ids,
            "labels": [STYLES[sid]["label"] for sid in ids],
            # Aliases power gallery search. The search box has always
            # claimed to match them; now it actually can.
            "aliases": [list(STYLES[sid].get("aliases", [])) for sid in ids],
        }

    artists = sorted(ARTISTS.values(), key=lambda rec: rec["label"])
    modifiers_by_axis = {
        axis: [MODIFIERS[mid]["label"]
               for mid in MODIFIERS_BY_AXIS.get(axis, []) if mid in MODIFIERS]
        for axis in AXES
    }
    # The picker shows what each modifier actually does. A list of names
    # like "Split Tone" or "Bleach Bypass" tells you nothing on its own.
    modifier_records = [
        {
            "label": MODIFIERS[mid]["label"],
            "axis": axis,
            "detail": MODIFIERS[mid].get("prose", ""),
            "aliases": list(MODIFIERS[mid].get("aliases", [])),
        }
        for axis in AXES
        for mid in MODIFIERS_BY_AXIS.get(axis, [])
        if mid in MODIFIERS
    ]

    preview_index = _preview_sprites()

    all_labels = sorted(rec["label"] for rec in STYLES.values())

    lines = [
        HEADER,
        f"export const CATEGORIES = {_js(list(CATEGORIES))};",
        "// Display names. Title-casing the id gives \"Three D Digital\".",
        f"export const CATEGORY_LABELS = {_js(CATEGORY_LABELS)};",
        "",
        f"export const STYLE_COUNT = {len(STYLES)};",
        f"export const ARTIST_COUNT = {len(ARTISTS)};",
        "",
        "// Per-category ids, labels and aliases as parallel arrays.",
        f"export const STYLE_DATA_BY_CATEGORY = {_js(styles_by_category)};",
        "",
        "// Flat label list for the style dropdown, in the node's own order.",
        f"export const ALL_STYLE_LABELS = {_js(all_labels)};",
        "",
        f"export const ARTIST_LABELS = {_js([r['label'] for r in artists])};",
        f"export const ARTIST_CATEGORIES = {_js([r.get('category', '') for r in artists])};",
        "// The category tabs for the artist picker, in offer order, plus",
        "// their display names. Derived from the data so a category added",
        "// by a user_styles.json artist still gets a tab.",
        f"export const ARTIST_CATEGORY_ORDER = {_js(list(ARTIST_CATEGORIES))};",
        f"export const ARTIST_CATEGORY_LABELS = {_js(ARTIST_CATEGORY_LABELS)};",
        f"export const ARTIST_ALIASES = {_js([list(r.get('aliases', [])) for r in artists])};",
        "// Descriptors are what actually make an artist choosable: the",
        "// name alone means nothing if you do not already know the work.",
        f"export const ARTIST_DESCRIPTORS = {_js([r.get('descriptor', '') for r in artists])};",
        "",
        f"export const MODIFIER_AXES = {_js(list(AXES))};",
        f"export const MODIFIER_LABELS_BY_AXIS = {_js(modifiers_by_axis)};",
        f"export const MODIFIER_RECORDS = {_js(modifier_records)};",
        "",
        "// Sprite-sheet coordinates for the gallery thumbnails. Empty when",
        "// previews have not been built, in which case the gallery falls",
        "// back to lettered placeholder tiles.",
        f"export const PREVIEW_INDEX = {_js(preview_index)};",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate frontend JS data.")
    parser.add_argument("--check", action="store_true",
                        help="Verify only; exit non-zero if stale.")
    args = parser.parse_args()

    expected = generate()

    if args.check:
        if not TARGET.is_file():
            print(f"FAIL: {TARGET.name} does not exist. "
                  f"Run: python scripts/generate_js_data.py")
            return 1
        if TARGET.read_text(encoding="utf-8") != expected:
            print("FAIL: generated JS data is stale. "
                  "Run: python scripts/generate_js_data.py")
            return 1
        print("PASS: generated JS data is current.")
        return 0

    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Written: js/{TARGET.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
