"""Record which release each style, artist and modifier first shipped in.

The gallery can sort by newest and filter to "New" only because every
entry carries a release stamp. That stamp lives in ``data/versions.py``,
which this script writes.

Three modes:

    python scripts/stamp_versions.py --check          # CI gate
    python scripts/stamp_versions.py --stamp          # new entries -> this version
    python scripts/stamp_versions.py --from-history   # rebuild from git

``--stamp`` is the one a maintainer runs. It reads the version out of
``pyproject.toml`` and gives it to every entry the map does not already
know, so adding content is a two-command habit rather than a bookkeeping
chore: add the records, run ``--stamp``. Entries already stamped are
never rewritten -- a release date is a fact about the past.

``--from-history`` reconstructs the whole map by reading the data layer
out of git at the tip commit of each past release. It was used once, to
seed the file, and stays because a seed you cannot reproduce is a seed
you cannot check. It needs git and a clean-ish tree; the other two modes
need neither.

``--check`` is what CI runs: it fails when a shipped entry has no stamp,
or when the map still names something the pack no longer ships. That is
the half the old convention could not enforce -- a new style with no
stamp would simply have sorted as if it had always been there.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# Never let a maintainer's own user_styles.json reach a shipped artifact.
os.environ.setdefault("STYLEBOOK_IGNORE_USER_STYLES", "1")

TARGET = ROOT / "data" / "versions.py"
PYPROJECT = ROOT / "pyproject.toml"

HEADER = '''"""When each entry first shipped, by release.

Generated by scripts/stamp_versions.py. Do not edit by hand -- run

    python scripts/stamp_versions.py --stamp

after adding styles, artists or modifiers, and CI will confirm it.

This exists so the gallery can answer "what changed in this release?"
without a human keeping a changelog of 600 tiles in their head. It is
presentation data only: nothing here reaches a prompt, and no seed,
saved workflow or dropdown order depends on it.
"""

from __future__ import annotations

#: Every release that has shipped content, oldest first. The gallery uses
#: this order rather than parsing version strings in JavaScript.
RELEASES: tuple[str, ...] = (
'''


def read_version(text: str) -> str:
    match = re.search(r'(?m)^version\s*=\s*"([^"]+)"', text)
    return match.group(1) if match else ""


def current_version() -> str:
    version = read_version(PYPROJECT.read_text(encoding="utf-8"))
    if not version:
        raise SystemExit("could not read version from pyproject.toml")
    return version


def shipped_ids() -> dict[str, list[str]]:
    from data.artists import ARTISTS
    from data.modifiers import MODIFIERS
    from data.styles import STYLES

    return {
        "styles": list(STYLES),
        "artists": list(ARTISTS),
        "modifiers": list(MODIFIERS),
    }


def load_map() -> tuple[list[str], dict[str, dict[str, str]]]:
    if not TARGET.is_file():
        return [], {"styles": {}, "artists": {}, "modifiers": {}}
    namespace: dict = {}
    exec(compile(TARGET.read_text(encoding="utf-8"), str(TARGET), "exec"), namespace)
    return list(namespace.get("RELEASES", ())), namespace.get(
        "ADDED_IN", {"styles": {}, "artists": {}, "modifiers": {}}
    )


def render(releases: list[str], added: dict[str, dict[str, str]]) -> str:
    out = [HEADER]
    for release in releases:
        out.append('    "%s",\n' % release)
    out.append(")\n\n")
    out.append("#: Entry id -> the release it first shipped in.\n")
    out.append("ADDED_IN: dict[str, dict[str, str]] = {\n")
    for kind in ("styles", "artists", "modifiers"):
        out.append('    "%s": {\n' % kind)
        for entry_id in sorted(added.get(kind, {})):
            out.append('        "%s": "%s",\n' % (entry_id, added[kind][entry_id]))
        out.append("    },\n")
    out.append("}\n")
    return "".join(out)


# ---------------------------------------------------------------------------
# History reconstruction
# ---------------------------------------------------------------------------

def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout


def _ids_at(sha: str) -> dict[str, list[str]] | None:
    """Import the data layer as it stood at *sha*, in a temp worktree.

    A subprocess, because ``data`` is already imported in this one and a
    second copy at a different revision would collide in ``sys.modules``.
    """
    with tempfile.TemporaryDirectory() as tmp:
        archive = subprocess.run(
            ["git", "archive", sha, "data"], cwd=ROOT, capture_output=True, check=False
        )
        if archive.returncode != 0:
            return None
        tar = subprocess.run(
            ["tar", "-x", "-C", tmp], input=archive.stdout, capture_output=True,
            check=False,
        )
        if tar.returncode != 0:
            return None
        probe = (
            "import json,sys;"
            "sys.path.insert(0, sys.argv[1]);"
            "from data.styles import STYLES;"
            "from data.artists import ARTISTS;"
            "from data.modifiers import MODIFIERS;"
            "print(json.dumps({'styles': list(STYLES), 'artists': list(ARTISTS),"
            " 'modifiers': list(MODIFIERS)}))"
        )
        env = dict(os.environ, STYLEBOOK_IGNORE_USER_STYLES="1")
        result = subprocess.run(
            [sys.executable, "-c", probe, tmp],
            capture_output=True, text=True, env=env, check=False,
        )
        if result.returncode != 0:
            return None
        import json
        return json.loads(result.stdout)


def from_history() -> tuple[list[str], dict[str, dict[str, str]]]:
    """Attribute every shipped id to the earliest release containing it."""
    shas = _git("log", "--format=%H", "--reverse").split()
    # The tip commit of each release is the one that says what that release
    # shipped. A version that reappears later (0.4.1 was reverted back to
    # 0.4.0) keeps its first position in the order and its latest content.
    order: list[str] = []
    tip: dict[str, str] = {}
    for sha in shas:
        try:
            version = read_version(_git("show", f"{sha}:pyproject.toml"))
        except subprocess.CalledProcessError:
            continue
        if not version:
            continue
        if version not in order:
            order.append(version)
        tip[version] = sha

    added: dict[str, dict[str, str]] = {"styles": {}, "artists": {}, "modifiers": {}}
    releases: list[str] = []
    for version in order:
        ids = _ids_at(tip[version])
        if ids is None:
            print(f"  ! could not read the data layer at {version}; skipping")
            continue
        releases.append(version)
        for kind in added:
            for entry_id in ids.get(kind, []):
                added[kind].setdefault(entry_id, version)
        print(f"  {version}: {sum(len(ids.get(k, [])) for k in added)} entries")
    return releases, added


# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true",
                       help="Verify every shipped entry is stamped (CI gate).")
    group.add_argument("--stamp", action="store_true",
                       help="Stamp new entries with the current version.")
    group.add_argument("--from-history", action="store_true",
                       help="Rebuild the whole map from git history.")
    args = parser.parse_args()

    shipped = shipped_ids()

    if args.from_history:
        releases, added = from_history()
        version = current_version()
        if version not in releases:
            releases.append(version)
        for kind, ids in shipped.items():
            for entry_id in ids:
                added[kind].setdefault(entry_id, version)
        # Drop anything the pack no longer ships.
        for kind in added:
            added[kind] = {k: v for k, v in added[kind].items() if k in set(shipped[kind])}
        TARGET.write_text(render(releases, added), encoding="utf-8", newline="\n")
        print(f"Written: data/{TARGET.name} ({len(releases)} releases)")
        return 0

    releases, added = load_map()

    if args.stamp:
        version = current_version()
        new = 0
        for kind, ids in shipped.items():
            for entry_id in ids:
                if entry_id not in added.get(kind, {}):
                    added.setdefault(kind, {})[entry_id] = version
                    new += 1
        for kind in list(added):
            added[kind] = {k: v for k, v in added[kind].items() if k in set(shipped[kind])}
        if new and version not in releases:
            releases.append(version)
        TARGET.write_text(render(releases, added), encoding="utf-8", newline="\n")
        print(f"Stamped {new} new entr{'y' if new == 1 else 'ies'} as {version}.")
        return 0

    # --check
    problems: list[str] = []
    for kind, ids in shipped.items():
        known = added.get(kind, {})
        for entry_id in ids:
            if entry_id not in known:
                problems.append(f"{kind[:-1]} '{entry_id}' has no release stamp")
        for entry_id in known:
            if entry_id not in set(ids):
                problems.append(
                    f"{kind[:-1]} '{entry_id}' is stamped but no longer shipped"
                )
    unknown = {v for kind in added for v in added[kind].values()} - set(releases)
    for version in sorted(unknown):
        problems.append(f"release '{version}' is used but missing from RELEASES")

    if problems:
        print("FAIL: data/versions.py is out of date.")
        for problem in problems[:20]:
            print("  -", problem)
        if len(problems) > 20:
            print(f"  ... and {len(problems) - 20} more")
        print("Run: python scripts/stamp_versions.py --stamp")
        return 1
    print(f"PASS: every entry is stamped ({len(releases)} releases).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
